# Use https://travis-ci.org/ for automatic testing
language: go

go:
# Use only the latest versuib
  - tip

install:
# Resolve dependencies
  - go get -u "h12.me/socks"
  - go get -u "github.com/oschwald/geoip2-golang"
